docker-locate: ENH: Add help and custom --error|-e option
For some use cases, we want another fallback, so the client needs to distinguish between real lookup and no found container.

diff --git a/docker-locate b/docker-locate
--- a/docker-locate
+++ b/docker-locate
@@ -1,11 +1,35 @@
 #!/bin/bash
 
+printUsage()
+{
+    cat <<HELPTEXT
+Locate docker container ID based on its name or another identifier.
+Usage: "$(basename "$1")" [-e|--error] [-a|--all] [-l|--latest] [-n=-1] CONTAINER_NAME [-?|-h|--help]
+HELPTEXT
+}
+
+isError=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--error|-e)	shift; isError=t;;
+	*)		break;;
+    esac
+done
 lastArg=${!#}
 
 IFS=$'\n'
 typeset -a id=($(docker ps -q "${@:1:$(($#-1))}" --filter "id=$lastArg"))
 [ ${#id[@]} -eq 0 ] && id=($(docker ps -q "${@:1:$(($#-1))}" --filter "name=$lastArg"))
 [ ${#id[@]} -eq 0 ] && id=($(docker ps -q "${@:1:$(($#-1))}" --filter "ancestor=$lastArg"))
-[ ${#id[@]} -eq 0 ] && { echo >&2 "Warning: Could not locate $lastArg"; id=("$lastArg"); }
+if [ ${#id[@]} -eq 0 ]; then
+    if [ "$isError" ]; then
+	exit 1
+    else
+	echo >&2 "Warning: Could not locate $lastArg"
+	id=("$lastArg")
+    fi
+fi
 
 printf '%s\n' "${id[@]}"
